#!/bin/bash
source ./arg_reader.sh

if [ ! -d $DIR ]; then
  printf "\33[31m Directory $DIR not exists \33[0m \n"
  exit -1
fi

# ===================
# ===== Program =====
# ===================

function rerank() {
  dir=/home/boton/Dropbox/DSP/RandomWalk/source/
  exp=exp/
  program=$dir/out
  ans=$dir/query/${N_QUERY}.ans
  config="-q $dir/query/${N_QUERY}.query -a ${ans} -d ${DIR}"
  tmp_logfile=.log
  start=0.02
  step=0.02
  end=1

  method=graph
  result=$exp/$IV_OR_OOV/$EXP_SET.map
  printf "" > $result
  printf "Evaluating using Graph-based Re-ranking [=>"
  for p in `seq $start $step $end`; do
    printf "\b=>"
    printf "$p\t" >> $result
    $program $config -o $tmp_logfile -p $p --method=$method >> $result
    trec_eval -q ${ans} $tmp_logfile > $result.$p.detail
  done
  printf "\b=] \33[32m[Done]\33[0m\n"

  methods=prf
}

rerank
