#!/bin/bash
source ./arg_reader.sh

if [ ! -d $DIR ]; then
  printf "\33[31m Directory $DIR not exists \33[0m \n"
  exit -1
fi

# ===================
# ===== Program =====
# ===================

function rerank() {
  dir=/home/boton/Dropbox/DSP/RandomWalk/source/
  exp=exp/
  program=$dir/out
  config="-q $dir/query/${N_QUERY}.query -a $dir/query/${N_QUERY}.ans -d ${DIR}"
  tmp_logfile=.log
  start=0.02
  step=0.02
  end=1

  method=graph
  log=$exp/$EXP_SET.map
  printf "" > $log
  printf "Evaluating using Graph-based Re-ranking [=>"
  for p in `seq $start $step $end`; do
    printf "\b=>"
    printf "$p\t" >> $log
    $program $config -o $tmp_logfile -p $p --method=$method >> $log
    #echo $program $config -o $tmp_logfile -p $p --method=$method 
  done
  printf "\b=] \33[32m[Done]\33[0m\n"

  methods=prf
}

rerank
