#!/bin/bash
source ./arg_reader.sh

if [ ! -d $DIR ]; then
  cp -r $PRE_DIR/${CORPUS} $DIR
  rm -rf $MULSIM_DIR/*
fi

# ===================
# ===== Program =====
# ===================
source ../bash_lib/parallel.sh

function recalcAcousticSimilarity() {

  IFS=$'\r\n'
  QUERIES=($(cat $QUERY_LIST))

  printf "\33[33m[Info]\33[0m # of query: ${#QUERIES[@]}\n"
  bin=./pair-wise-dtw

  theta=`echo "${opts[@]}" | cut -f 1 -d " " | sed "s/.*=//g"`
  cp $theta "${MULSIM_DIR}/../"
  

  #if [ "${feature_dim}" == "39" ]; then dist_type="--type=ma" else dist_type="--type=lip" fi
  #for q in ${QUERIES[@]}; do
  #  echo $q
  #  recalcAS $q
  #done
  parallelize "recalcAS" ${QUERIES[@]}
}

function recalcAS() {
  shopt -s extglob
  query=$1
  query="${query%%*( )}"
  #feature="${feature_dir}/${query}.39.ark"
  feature="${feature_dir}/${query}.${feature_dim}.ark"

  dir="${MFCC_DIR}/${query}"
  mat="${MULSIM_DIR}/${query}.mul-sim"
  list="${LIST_DIR}/${query}.lst"

  printf "Processing query: \33[34m%s\33[0m\n" ${query}

  #old_bin=./calc-acoustic-similarity
  #echo ${old_bin} -d $dir -o $mat $dtw_options --list=$list ${opts[@]}
  ${bin} --ark=$feature -o $mat ${opts[@]} --scale=log

  shopt -u extglob
}
recalcAcousticSimilarity
